### PR TITLE
fix: use dispatcher for all workloads

### PR DESCRIPTION
**Pull request by sauyon**
Also incidentally fixes the max batch size bug.

/cc @frostming @aarnphm

### CODE REVIEW

**Comment by sauyon** [comment]
@larme this should be ready for review now!

**Review by aarnphm — APPROVED** [review]

**Comment by sauyon** [comment]
@aarnphm do you know what these test failures are?

**Comment by aarnphm** [comment]
The tests failure are probably some dependencies issue with pandas

**Comment by aarnphm** [comment]
I'm wrong, aparently there are actual bugs

**Pull request merged**
