### PR TITLE
Add Statsmodels example notebook links

### PR DESCRIPTION
**Pull request by narennadig**
Added the statsmodel example in the examples.md file

### CODE REVIEW

**Comment by parano** [comment]
Thanks @narennadig! Do you mind also add a link to the main README.md file? There's a section listing all the frameworks with link to docs and examples

**Comment by narennadig** [comment]
@parano  sure ...will do the same..Should I create a new branch?

**Comment by narennadig** [comment]
@parano  Done

**Comment by parano** [comment]
@narennadig thanks!

**Pull request merged**
