### PR TITLE
fix(containerize): Returns the home modified with build_ctx to correct errors

### PR DESCRIPTION
**Pull request by kyungseonpark**
This is an issue that occurred when you received API with FastAPI and created BentoML Docker Image.

Returns the home modified with build_ctx to correct errors that could not be found even if BentoML was deployed to the API several times.

## What does this PR address?

Fixes #(issue)

## Before submitting:

- [x] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [x] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [x] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
  those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

## Who can help review?

Feel free to tag members/contributors who can help review your PR.

### CODE REVIEW

**Comment by parano** [comment]
Hi @kyungseonpark, thank you for the PR! could you share more about the issue you ran into with FastAPI and Bento image?

**Comment by kyungseonpark** [comment]
> 안녕@kyungseonpark, 홍보해주셔서 감사합니다! FastAPI 및 Bento 이미지에서 발생한 문제에 대해 더 많이 공유할 수 있습니까?

When I received the API information and entered the build_ctx parameter, there was an error that did not work normally when the next model was created. I'll make a related example and share it with you again on the weekend. I tried to reproduce it, but it's not easy.

**Comment by kyungseonpark** [comment]
> Hi @kyungseonpark, thank you for the PR! could you share more about the issue you ran into with FastAPI and Bento image?

When I received the API information and entered the build_ctx parameter, there was an error that did not work normally when the next model was created. I'll make a related example and share it with you again on the weekend. I tried to reproduce it, but it's not easy.

**Comment by sauyon** [comment]
Hi! Any luck reproducing the issue?

**Pull request closed without merging**
