### PR TITLE
fix: format of PILImage is None which may cause buffer saving error, in the payload stage.

### PR DESCRIPTION
**Pull request by senlyu163**
## What does this PR address?
Sometimes the PILImage processed does not contain format information, so the following error will be raised. It may take a long time for users to troubleshoot positioning. Therefore, when PILImage does not contain format information, the user should be reminded to use other formats.
```bash
2023-12-27 02:33:34.030 | CRITICAL | service:inference:118 - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2409, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tilediffusion/service.py", line 114, in inference
    ) = await tilediffusion_inference_runner.tilediffusion_infer.async_run(
  File "/usr/local/lib/python3.10/site-packages/bentoml/_internal/runner/runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/bentoml/_internal/runner/runner_handle/remote.py", line 201, in async_run_method
    payload_params = Params[Payload](*args, **kwargs).map(
  File "/usr/local/lib/python3.10/site-packages/bentoml/_internal/runner/utils.py", line 65, in map
    kwargs = {k: function(v) for k, v in self.kwargs.items()}
  File "/usr/local/lib/python3.10/site-packages/bentoml/_internal/runner/utils.py", line 65, in <dictcomp>
    kwargs = {k: function(v) for k, v in self.kwargs.items()}
  File "/usr/local/lib/python3.10/site-packages/bentoml/_internal/runner/container.py", line 665, in to_payload
    return container_cls.to_payload(batch, batch_dim)
  File "/usr/local/lib/python3.10/site-packages/bentoml/_internal/runner/container.py", line 461, in to_payload
    batch.save(buffer, format=batch.format)
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2412, in save
    raise ValueError(msg) from e
ValueError: unknown file extension: 
```
This problem does not trigger in development mode, but will trigger in production mode.

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by frostming** [comment]
This usually happens when the image is constructed from scratch(pixels), not read from source. Would it be better to give it a default format, such as "PNG"?

**Comment by senlyu163** [comment]
> This usually happens when the image is constructed from scratch(pixels), not read from source. Would it be better to give it a default format, such as "PNG"?

We usually fetch images to PILImage through URL, and there is no guarantee whether the user's URL contains complete image information. If the user's image lacks format information, an error will occur, and the error message is not friendly enough.

**Comment by senlyu163** [comment]
I have reconsidered and agree with you. Some security checks should be done on the user end, rather than the framework itself, like image is constructed from scratch(pixels). Thank you for your review ;)

**Comment by nsabir2011** [comment]
I am facing the same error in the PR description. I have a custom Runnable that generates and returns the image as a payload. Am using `StableDiffusionControlNetPipeline` from the `diffusers` library for the generation.
I am getting this error after upgrading to BentoML version `1.1.11`. It did not happen when I had version `1.0.19`.

The `pipe` returns a PIL image type with `format=''`. Which is why the above error occurs. Currently, I am working around this with:
```python
out_image.format = "png"
```

I personally think the `PILImageContainer` should fallback to `png` format if there is cases like this. Maybe with a warning.

**Pull request closed without merging**
