### PR TITLE
feat: add a charset option for the json output header

### PR DESCRIPTION
**Pull request by leecoder**
## Description

Adding an option to specify the CHARSET in the Output Header.

## Motivation and Context

If the JSON output is a UTF-8 string, it is required.

## How Has This Been Tested?

`
    @api(input=JsonInput(), output=JsonOutput(charset="utf-8"), …)
`

## Checklist:

- [x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by aarnphm** [comment]
@parano should we merge this to `0.13-line` instead of `LTS`?

**Comment by parano** [comment]
@aarnphm it should be helpful for others to get this into 0.13-LTS, should we add the charset option in 1.0 branch as well?

**Comment by parano** [comment]
Merging now, the CI errors are being fixed in a separate PR @bojiang is working on now.

**Comment by aarnphm** [comment]
> @aarnphm it should be helpful for others to get this into 0.13-LTS, should we add the charset option in 1.0 branch as well?

would be helpful. We can default to `utf-8` and then users can uses others if needed

**Pull request merged**
