### PR TITLE
[TEST/CI] Add tests covering XgboostModelArtifact #724

### PR DESCRIPTION
**Pull request by xiwang129**
## Description
- Created example BentoService in `tests/bento_service_examples/` that uses a Xgboost SavedModel Artifact
- Created test in `tests/integration_tests/` that uses the XgboostModelArtifact including major functionalities like save, load and predict; built a sample xgboost model using the breast cancer dataset 
- Built a docker container with the saved bundle and tested the API endpoint
- Added a shell script in `travis/` to import xgboost and run `pytest tests/test_xgboost_model_artifact.py`
- Added a shell script in ` .travis.yml` to launch the test script 

## Motivation and Context

- worked on #724 

## How Has This Been Tested?

Tested locally using `pytest tests/integration/test_xgboost_model_artifact.py`

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [x] Test, CI, or build

## Component(s) if applicable
- [x] BentoService (service definition, dependency management, API input/output adapters)
- [x] Model Artifact (model serialization, multi-framework support)
- [ ] Model Server (mico-batching, dockerisation, logging, OpenAPI, instruments)
- [ ] YataiService gRPC server (model registry, cloud deployment automation)
- [ ] YataiService web server (nodejs HTTP server and web UI)
- [ ] Internal (BentoML's own configuration, logging, utility, exception handling)
- [ ] BentoML CLI

## Checklist:

- [x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by yubozhao** [comment]
@xiwang129 Thanks for the PR.
Can you run `./dev/format.sh` to fix all of the linter issues? We also moved from travis-ci to Github Actions. You will need to update this test to that.

**Comment by xiwang129** [comment]
I am going to try to fix these issues. Thank you for the reviews!

**Comment by yubozhao** [comment]
Reopened at https://github.com/bentoml/BentoML/pull/1079

**Comment by xiwang129** [comment]
Ah, thanks for the help!

**Pull request closed without merging**
