### PR TITLE
fix: quote sys.executable for circus

### PR DESCRIPTION
**Pull request by aarnphm**
Ensure to quote sys.executable to work around https://github.com/circus-tent/circus/blob/b8c97d34a08b7d44ac3203440872510238b1132a/circus/process.py#L412

Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

### CODE REVIEW

**Review by sauyon — APPROVED** [review]

**Review by bojiang — CHANGES_REQUESTED** [review]
Windows e2e tests failed

**Comment by sauyon** [comment]
I suspect this is a real failure @aarn

**Comment by sauyon** [comment]
Why'd we close this one?

**Comment by aarnphm** [comment]
Ugh I have to take a another look into this.

**Pull request closed without merging**
