### PR TITLE
chore(deps): open Starlette version, to allow latest

### PR DESCRIPTION
**Pull request by alexeyshockov**
## What does this PR address?

Open the version constraints for Starlette, to allow the latest version (it's a consumer decision, as BentoML is used as a library is many cases).

This also allows to use the latest FastAPI (a popular combination AFAIK), as it usually requires latest version of Starlette. 

## Before submitting:

- [x] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [x] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [x] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [x] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by sauyon** [comment]
We limited this because at some point Starlette made breaking changes, but we should really keep up with updates better. @aarnphm did we disable dependabot?

**Comment by aarnphm** [comment]
yes we did, because starlette introduces breaking change, hence upper bound limit.

**Comment by sauyon** [comment]
Wait, we disabled dependabot for Starlette? We shouldn't do that, we should be doing the work to ensure compatibility, right?

**Comment by alexeyshockov** [comment]
I think it was one time BC break that is already addressed, right? So opening the constraints is not an issue now, you just want to be safe in the future?

In this case I would argue that all the other deps have no upper bound, so any of them can introduce a BC break with a new version. I don't see any reason why Starlette should not be special.

Also a point against dependabot approach: we are still sitting on BentoML 1.0.20, which constraints Starlette to a "really old" version (yes-yes, going to upgrade in the next week).

IMO it should be a consistent approach on dependency constraints.

**Comment by sauyon** [comment]
> In this case I would argue that all the other deps have no upper bound, so any of them can introduce a BC break with a new version. I don't see any reason why Starlette should be special.

I think the approach is leave dependencies unlocked until they break on us and we no longer trust that backwards compatibility will work as expected.

> Also a point against dependabot approach: we are still sitting on BentoML 1.0.20, which constraints Starlette to a "really old" version (yes-yes, going to upgrade in the next week).

We do try to ensure backwards compatibility as much as we can, if we break something you're using in an update that's a bug and should be reported.

**Comment by judahrand** [comment]
It is really important to us to be able to manage dependencies such as Starlette for example in the case of security vulnerabilities. It doesn't feel like the right solution for BentoML to pin this dependency. Downstream users should really be pinning dependencies in their environment.

**Comment by aarnphm** [comment]
I disagree with the case of Starlette. Surely if there are any security vulnerabilities, we are happy to bump the upper bound for Starlette. In the past, they have introduced breaking change, which breaks BentoML, so we decided that we will upper limit the version that we know works with bentoml.

**Comment by sauyon** [comment]
At this point this PR has been open long enough that I think we should just merge it.

**Review by aarnphm — APPROVED** [review]

**Pull request merged**
