### PR TITLE
feature: add support for online ML models from River library in BentoML

### PR DESCRIPTION
**Pull request by jsamantaucd**
Feature request
We have been developing and experimenting river (https://riverml.xyz/latest/api/overview/) for training and inferencing time series and continuous machine learning tasks and would like to add support for river in BentoML.

We have also created a custom python module to add river models using MLflow which can be saved in the BentoML model's repository and later can be retrieved from the BentoML for inferencing.

Motivation
River offers a diverse selection of ML models for online learning that are much more efficient than the sklearn models, and integrating this MLflow would create a comprehensive ML solution.

Others:
This feature was tested on tag v1.0.20

### CODE REVIEW

**Comment by jsamantaucd** [comment]
This PR is related to the feature request: https://github.com/bentoml/BentoML/issues/4640

**Comment by frostming** [comment]
Hi @jsamantaucd We are preparing to restructure the examples and do not accept new framework-specific examples.

You can make it in a standalone repository and we can link it in our README, thanks.

**Comment by jianshen92** [comment]
@jsamantaucd Here is an example on how we showcase examples, https://github.com/bentoml/BentoVoiceAgent

**Comment by jsamantaucd** [comment]
Hi @frostming and @jianshen92, thank you for your valuable feedback, I have created a standalone repository as suggested: https://github.com/jsamantaucd/BentoStatsmodel, please add it in your README. Thanks!

**Pull request closed without merging**
