### PR TITLE
feat: support BackgroundTask

### PR DESCRIPTION
**Pull request by KimSoungRyoul**
## What does this PR address?

Feature #4148 

- support Starlette Background Tasks https://www.starlette.io/background/

Here's an example how to use starlette BackgroundTask In BentoML.

~~~python

import httpx
import numpy as np
from starlette.background import BackgroundTask, BackgroundTasks

import bentoml
from bentoml.io import NumpyNdarray, JSON, TaskResponse

iris_clf_runner = bentoml.sklearn.get("iris_clf_with_feature_names:latest").to_runner()

svc = bentoml.Service("iris_classifier", runners=[iris_clf_runner])


async def send_inference_result_task(result: np.ndarray, url: str):
    async with httpx.AsyncClient() as client:
        await client.post(url, json={"result": result.tolist()})


@svc.api(
    input=NumpyNdarray.from_sample(
        np.array([[4.9, 3.0, 1.4, 0.2]], dtype=np.double), enforce_shape=False
    ),
    output=JSON.from_sample({"message": "success or fail"}),
)
async def classify_with_single_task(input_series: np.ndarray) -> TaskResponse[dict[str, str], BackgroundTask]:
    result: np.ndarray = await iris_clf_runner.predict.async_run(input_series)
    task = BackgroundTask(send_inference_result_task, result=result, url="http://another-server1:8000/callback")

    # return {"message":"success"}
    return TaskResponse(
        res={"message": "success"},
        background=task,  # tasks are executed in the background
    )


@svc.api(
    input=NumpyNdarray.from_sample(
        np.array([[4.9, 3.0, 1.4, 0.2]], dtype=np.double), enforce_shape=False
    ),
    output=JSON.from_sample({"message": "success or fail"}),
)
async def classify_with_multi_tasks(input_series: np.ndarray) -> TaskResponse[dict[str, str], BackgroundTasks]:
    result: np.ndarray = await iris_clf_runner.predict.async_run(input_series)

    tasks = BackgroundTasks()
    tasks.add_task(BackgroundTask(send_inference_result_task, result=result, url="http://another-server1:8000/callback"))
    tasks.add_task(BackgroundTask(send_inference_result_task, result=result, url="http://another-server2:8000/callback"))

    # return {"message":"success"}
    return TaskResponse(
        res={"message": "success"},
        background=tasks, # tasks are executed in the background
    )

~~~

## Before submitting:

- [x] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [x] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [x] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [x] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [x] Did you write tests to cover your changes?

### CODE REVIEW

**Review by aarnphm — CHANGES_REQUESTED** [review]
Reject since it doesn't make sense to have this support.

Probably need more brainstorming on what this does actually.

**Comment by aarnphm** [comment]
FWIW we are working on the next generation of IO Descriptor, so we might not accept new PR feature at this point other than bug fixes and mantainance

**Comment by KimSoungRyoul** [comment]
@aarnphm @sauyon 
I sorry for taking so long to answer (works too busy) 

Based on your comments, 
it looks like bentoml team are trying to switch(move) the backend of the API server from starlette to a rust binding. 

If this is correct or similarly, it seems to be right choice that closing the PR now.

after the rust binding feature is added I'd like to contribute again about background task feature (If I can get a chance)

 Can you close this pullrequest?

**Comment by KimSoungRyoul** [comment]
by the way, is there any can see bentoml's schedule chart like a kserve ? (https://github.com/orgs/kserve/projects/17)

If I knows exactly where your team want bentoML to go, I can contribute a more helpful PullRequest.

**Comment by sauyon** [comment]
> ... I sorry for taking so long to answer (works too busy)

Not a problem at all!

> Based on your comments, it looks like bentoml team are trying to switch(move) the backend of the API server from starlette to a rust binding.
> 
> If this is correct or similarly, it seems to be right choice that closing the PR now.
> 
> after the rust binding feature is added I'd like to contribute again about background task feature (If I can get a chance)
> 
> Can you close this pullrequest?

Will do! Thanks anyway for this, and look forward to your future contribution!

**Pull request closed without merging**
