### PR TITLE
chore(cli): cleanup and remove unused

### PR DESCRIPTION
**Pull request by aarnphm**
Some house keeping stuff for type warning and `# type: ignore`.

using CLI.command(name=...) to remove redundant reportUnusedFunction
in the local scope.

Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by sauyon** [comment]
Hm, this seems like it's only a problem because it's being done in a function, right? What's the reason for that?

**Comment by aarnphm** [comment]
> Hm, this seems like it's only a problem because it's being done in a function, right? What's the reason for that?

Yes, since we are lazy load the CLI to avoid side effect from importing bentoml (IIRC), but otherwise this is mainly to address that.

**Comment by frostming** [comment]
This change seems anti-pattern. Maybe we could configure the linter(pyright I guess) to ignore reportUnusedFunction in the scope.

**Comment by aarnphm** [comment]
> This change seems anti-pattern. Maybe we could configure the linter(pyright I guess) to ignore reportUnusedFunction in the scope.

For pyright they don't have support for per-file ignore, like ruff. It is just either exclude they whole module or do line-by-line `# type: ignore`, which is not ideal

**Comment by sauyon** [comment]
> Yes, since we are lazy load the CLI to avoid side effect from importing bentoml (IIRC), but otherwise this is mainly to address that.

I think this is what we should solve; why are we lazy loading `bentoml` in the CLI? Don't we load it anyways?

> For pyright they don't have support for per-file ignore, like ruff. It is just either exclude they whole module or do line-by-line `# type: ignore`, which is not ideal

Why is it not ideal? This seems fine.

**Comment by aarnphm** [comment]
I don't think we should lazy load bentoml. I suspect the reason we have to put it into the function to solve the cycling chain import.

**Comment by sauyon** [comment]
Let me quickly try something.

**Pull request closed without merging**
