### PR TITLE
fix(exception): catch exception for users' runners code

### PR DESCRIPTION
**Pull request by aarnphm**
Signed-off-by: aarnphm-ec2-dev <29749331+aarnphm@users.noreply.github.com>

## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Review by jianshen92 — APPROVED** [review]

**Comment by sauyon** [comment]
Why is this only for the stream endpoint?

**Comment by aarnphm** [comment]
@sauyon I added the exception catch to all `async_run` and `async_stream` PTAL

**Review by sauyon — APPROVED** [review]
LGTM for now! Do you know why these aren't being raised? Should we just have a unified print point in the dispatcher?

**Comment by aarnphm** [comment]
I think the log just eats it all and doesn't print out the exception. Eh let's just have this for now and once we move over everything to rust

**Pull request merged**
