### PR TITLE
feat: skip access log for infra endpoints

### PR DESCRIPTION
**Pull request by frostming**
Signed-off-by: Frost Ming <me@frostming.com>

## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by jianshen92** [comment]
Hey Frost, while you are at this, did you notice why the access logs for `runners` was not enabled by default? I guess in 1.2 we will not have runners anymore

**Comment by frostming** [comment]
> did you notice why the access logs for `runners` was not enabled by default

Do you mean the runners log for legacy service are missing?

**Comment by jianshen92** [comment]
> > did you notice why the access logs for `runners` was not enabled by default
> 
> Do you mean the runners log for legacy service are missing?

Yes, as we only see access logs from api servers but not runner.

**Comment by frostming** [comment]
> Yes, as we only see access logs from api servers but not runner servers.

How can I reproduce? It doesn't seem the case from my testing:

```
2024-01-24T17:09:08+0800 [INFO] [runner:iris_clf_with_feature_names:1] _ (scheme=http,method=POST,path=/predict,type=application/octet-stream,length=32) (status=200,type=application/vnd.bentoml.NdarrayContainer,length=8) 23.168ms (trace=f3a77abf88368206272aff8d6b111646,span=928ec0e33f904155,sampled=0,service.name=iris_clf_with_feature_names)
```

**Comment by jianshen92** [comment]
> > Yes, as we only see access logs from api servers but not runner servers.
> 
> How can I reproduce? It doesn't seem the case from my testing:
> 
> ```
> 2024-01-24T17:09:08+0800 [INFO] [runner:iris_clf_with_feature_names:1] _ (scheme=http,method=POST,path=/predict,type=application/octet-stream,length=32) (status=200,type=application/vnd.bentoml.NdarrayContainer,length=8) 23.168ms (trace=f3a77abf88368206272aff8d6b111646,span=928ec0e33f904155,sampled=0,service.name=iris_clf_with_feature_names)
> ```

Ah looks like its a BentoCloud behaviour, not a BentoML behaviour.

**Pull request merged**
