### PR TITLE
build: Use official nvidia-ml-py package instead of fork

### PR DESCRIPTION
**Pull request by ecederstrand**
## What does this PR address?

There are two packages in PyPI installing a `pynvml` module - `pynvml` and `nvidia-ml-py`. The former is a forked version of the latter, which is the official package published by NVIDIA.

I stumbled upon this because I built a virtual environment that also installs `gpustat`, and that failed because that package pulls in `nvidia-ml-py`, thus overwriting the BentoML dependency.

## Before submitting:

- [x] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [x] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [x] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by sauyon** [comment]
Hiya, sorry about the slow response! Mind if I push to fix the CI errors?

**Comment by ecederstrand** [comment]
Please do 😊

**Comment by sauyon** [comment]
Ah, seems like there are real test failures caused by the dependency change, we'll probably have to go through and fix those.

**Comment by ecederstrand** [comment]
Tests are failing because they can't find the NVidia driver (cannot find `libnvidia-ml.so.1`). I assume the CI pipeline is missing e.g. `apt install libnvidia-compute-525-server`. Any suggestions on where a good place to add that would be?

**Comment by ecederstrand** [comment]
It turns out the tests don't actually test the pynvml package. They just dies because pynvml now throws a different exception when being imported. Should be fixed now.

**Comment by ecederstrand** [comment]
Test failures are dues to a bad pdm.lock file. I'm not familiar with pdm and just wanted to swap pynvml with nvidia-ml-py in pyproject.toml. What's the correct way to do that and re-generate the lock file?

**Comment by ecederstrand** [comment]
The 3 failing checks don't look related to the changes in this MR.

**Comment by aarnphm** [comment]
Yep. Our tests are just very much broken.

**Review by aarnphm — APPROVED** [review]

**Comment by aarnphm** [comment]
Thanks.

**Pull request merged**
