### PR TITLE
fix: yaml dump

### PR DESCRIPTION
**Pull request by xianml**
## What does this PR address?

image

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by frostming** [comment]
It was already fixed by 154c693b8ceaabb985089a9fd309f78ead258677 and anyway I don't think `.to_dict()` helps

**Comment by xianml** [comment]
> It was already fixed by [154c693](https://github.com/bentoml/BentoML/commit/154c693b8ceaabb985089a9fd309f78ead258677) and anyway I don't think `.to_dict()` helps


safe_dump will help on this case.

**Review by frostming — APPROVED** [review]

**Comment by frostming** [comment]
> safe_dump will help on this case.

Oh sure, then we need to revert [154c693](https://github.com/bentoml/BentoML/commit/154c693b8ceaabb985089a9fd309f78ead258677) since we don't need duplicate fixes.

**Comment by xianml** [comment]
will close this one

**Pull request closed without merging**
