### PR TITLE
docs: Save models via `import_model.py`

### PR DESCRIPTION
**Pull request by hi-rustin**
## What does this PR address?

To add a better description to the import model section, I am a user who is not familiar with Python and machine learning, so I don't actually know how that code would be executed. I found some instructions in your other documentation. So I thought it would be better to add it here.
I also made a few minor tweaks:
1. state the Python version description, which I also found in your other documentation.
2. we should not use $ for bash blocks that have no output. You can check the [MD014/commands-show-ouput](https://github.com/updownpress/markdown-lint/blob/master/rules/014-commands-show-output.md) rule. Also, some of your places actually obey this rule, so I think it would be better to be uniform.

## Before submitting:

- [x] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [x] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [x] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [x] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Review by aarnphm — CHANGES_REQUESTED** [review]
This is not technically a file, you can python this into a python repl and it should work. You don't need a file here.

Also this section in the README.md are more for demonstration.

**Comment by aarnphm** [comment]
I'm going to close this because it is not relevant for README.md 😃

**Comment by hi-rustin** [comment]
> This is not technically a file, you can python this into a python repl and it should work. You don't need a file here.

Thank you for the explanation. Should we put it in the documentation? As a golang and rust developer I even forgot that python has a repl feature. 😆 


> I'm going to close this because it is not relevant for README.md 😃

It also fixes a markdown warning and adds a python version requirement.

> Also this section in the README.md are more for demonstration.

But it may be the first step for some users. That's why I think it's important.

Thanks for your review!  💚 💙 💜 💛 ❤️

**Comment by aarnphm** [comment]
Let's open a different PR for it

**Comment by hi-rustin** [comment]
> Let's open a different PR for it

Why do we need to reopen a new pull request? I can change it in this PR.

**Comment by hi-rustin** [comment]
Actually, use the `import_model.py` instruction that comes from your [document](https://docs.bentoml.org/en/latest/frameworks/diffusers.html#importing-a-pre-trained-model).

**Pull request closed without merging**
