### PR TITLE
fix: removing optional deps from dev deps

### PR DESCRIPTION
**Pull request by bojiang**
## Motivation and Context

To avoid possible false negatives

## Checklist:

- [ ] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sauyon** [comment]
The reason I added pydantic as a dev dependency was because it's required for a unit test---we should probably have a core suite of tests that are runnable without optional dependencies.

**Comment by bojiang** [comment]
@sauyon Is `pydantic` only required by unittests of Json IO?

**Comment by sauyon** [comment]
Yeah. Maybe that test should be moved somewhere else?

**Comment by bojiang** [comment]
@sauyon then we can just put `pydantic` into the `ci/config.yaml`

**Comment by sauyon** [comment]
Sure, but I think that there should be a separation between tests you can run locally without having all the optdepends and stuff you can't, is all.

Ideally a contributor who just ran `poetry install` would be able to run some test script that runs just the stuff that they can run.

**Comment by bojiang** [comment]
Surprisingly the unit tests didn't fail.

**Comment by bojiang** [comment]
>Sure, but I think that there should be a separation between tests you can run locally without having all the optdepends and stuff you can't, is all.
Ideally a contributor who just ran poetry install would be able to run some test script that runs just the stuff that they can run.

I'm not sure if I understand well. Contributors can always run `make test_*` locally right? @aarnphm

**Comment by aarnphm** [comment]
> Contributors can always run `make test_*` locally right? @aarnphm
`make tests-<name>` where `<name>` is defined under `./scripts/ci/config.yml`. But the `run_tests.sh` assumes that you install all the dependencies including tests.

**Comment by parano** [comment]
looks like this is no longer relevant after the latest CI changes, closing now

**Pull request closed without merging**
