### PR TITLE
fix(e2e): exception test for image IO

### PR DESCRIPTION
**Pull request by aarnphm**

### CODE REVIEW

**Comment by sauyon** [comment]
Uh, this looks like a real issue with the descriptor; let me look into that...

**Comment by aarnphm** [comment]
> Uh, this looks like a real issue with the descriptor; let me look into that...

I check, apparently PIL does accept application/pdf

**Comment by sauyon** [comment]
Oh, glad we fixed this then lol

**Review by sauyon — APPROVED** [review]

**Comment by bojiang** [comment]
@aarnphm The docs just say it only supports writing rather than reading

**Comment by bojiang** [comment]
revert request

**Comment by sauyon** [comment]
Let's leave this one in until we actually fix the bug so CI isn't failing

**Comment by bojiang** [comment]
will take that

**Pull request merged**
