### PR TITLE
[IN PROGRESS] Custom swagger endpoint path

### PR DESCRIPTION
**Pull request by gregd33**
## Description
Allows users to customize the prefix of the endpoint that Swagger is going to call.

Running `bentoml serve MyService:latest --swagger-url-prefix "/xxxx"` will give the Swagger page below

image

## Motivation and Context
See #1376 
 
Basically if a service is hosted somewhere such as `http://bentoml.com/myservices/Service1` then the Swagger being generated will point to `http://bentoml.com/Service1/predict` which will obviously break.

## How Has This Been Tested?
 _in progress_

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Component(s) if applicable
- [ ] BentoService (service definition, dependency management, API input/output adapters)
- [ ] Model Artifact (model serialization, multi-framework support)
- [x] Model Server (mico-batching, dockerisation, logging, OpenAPI, instruments)
- [ ] YataiService gRPC server (model registry, cloud deployment automation)
- [ ] YataiService web server (nodejs HTTP server and web UI)
- [ ] Internal (BentoML's own configuration, logging, utility, exception handling)
- [x] BentoML CLI

## Checklist:

_in progress_

- [x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by gregd33** [comment]
I've fixed the formatting and the documentation via click. 

I'm unsure about testing and how to go about adding tests or this. Any suggestions on what to add for tests for? 

The main changes are an extra CLI arguments to serve and serve-gunicorn as well this function: https://github.com/bentoml/BentoML/blob/0b112edf316c651c7fe8a3493e799dda4e0df7f6/bentoml/server/open_api.py#L20

I could create a test file for `open_api.py`  to test `get_open_api_spec_json`. I would need a `bento_service` to pass to it, along with the prefix... is there another test that does something similar?

**Comment by yubozhao** [comment]
@gregd33 Thanks for updating the formatting.

For testing, I suggest use `click`'s [CliRunner](https://click.palletsprojects.com/en/7.x/testing/) to start a API server with either `bentoml serve` or `bentoml serve-gunicorn` commands and make prediction requests again it. We should test for all potential cases: with prefix, without prefix, with incompatible prefixes. 

You can use example bento service as purest fixture.  You can find an example of that here:
https://github.com/bentoml/BentoML/blob/93cd4b1b6ef8488473736399a979e5800cee2075/tests/server/test_model_api_server.py#L10

It is using the pytest fixture from https://github.com/bentoml/BentoML/blob/93cd4b1b6ef8488473736399a979e5800cee2075/tests/conftest.py#L171

Let me know if this is enough to get you start with testing.  Happy to jump in a call if you are running into anything.

**Comment by gregd33** [comment]
I added one test for open_api directly, since that's where the biggest changes are:

https://github.com/bentoml/BentoML/pull/1411/files#diff-189ce22e4616a077c652a68fa69e081c49bf415ac91872f780238ec10af7f03f

I will work on the CLI next.

That said, testing whether I can make predictions won't work I don't think. The point of this change is a case such as that:

- bentoml is running a service on `localhost:5000`
- nginx is running so that the service above is located at `myserver.com/my_service_name`

So when I changed the swagger path via a CLI arg (e.g. to "my_service_name" ) it will _only_ work with nginx. That is, `localhost:5000/my_service_name/predict` does not exist, only `myserver.com/my_service_name/predict` does.

Changing the actual end point (e.g. making  `localhost:5000/my_service_name/predict` work) is a separate problem. I could make this change as well (and it should work with my setup since my nginx could point to `localhost:5000/my_service_name`) but this is a much broader change. Currently, my change only impacts the swagger page.

**Comment by yubozhao** [comment]
@gregd33 I think this would be pretty cool to continue to work on. We will take it over and push this through.  Thank you for starting the conversation and actively working on this to make it better for the community!

**Comment by bojiang** [comment]
@gregd33 Hi, how is it going? Anything I can help?

**Comment by gregd33** [comment]
> @gregd33 Hi, anything I can help with?

Hi, see the above comment by @yubozhao - he said he would take it over. That said, the code is ready/working, except for the tests that need to be written

**Pull request closed without merging**
