### PR TITLE
JsonInput shouldn't check Content-Type for AWS Lambda functions

### PR DESCRIPTION
**Pull request by omrihar**
This addresses an issue with AWS Lambda where sometimes a `Content-Type` header is not being sent to the Lambda function even though it is set by the client. This resolves https://github.com/bentoml/BentoML/issues/893.

## Description

With this change the JsonInput adapter will, by default, try to parse the input as JSON without testing for the `Content-Type` header, for AWS Lambda functions. If a JSONDecodeError is raised, it will raise a BadInput error.

## Motivation and Context

I had problems with AWS Lambda not transferring the correct headers and as a result, a server error was raised because the Content-Type was missing. We also discussed this on Slack.

## How Has This Been Tested?

In a function I use in production, I made this change manually to the lambda function and deployed it.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature and improvements (non-breaking change which adds/improves functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Component(s) if applicable
- [X] BentoService (service definition, dependency management, API input/output adapters)
- [ ] Model Artifact (model serialization, multi-framework support)
- [ ] Model Server (mico-batching, dockerisation, logging, OpenAPI, instruments)
- [ ] YataiService gRPC server (model registry, cloud deployment automation)
- [ ] YataiService web server (nodejs HTTP server and web UI)
- [ ] Internal (BentoML's own configuration, logging, utility, exception handling)
- [ ] BentoML CLI

## Checklist:

- [ ] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by parano** [comment]
Hi @omrihar, looks like there is one unit test specifically test this header checking behavior and it is cause the Travis CI tests to fail: `tests/adapters/test_json_handler.py`.  Could you fix that test to test this new behavior instead?

**Comment by omrihar** [comment]
Sure, I'll have a look at it on Sunday or Monday!

**Comment by parano** [comment]
Hi @omrihar, have you got a chance to look into fixing the CI tests? Happy to help take over the PR and fix it in this branch if you are busy at the moment, let me know!

**Comment by omrihar** [comment]
@parano , thanks for reminding me. It was indeed a bit hectic, and I forgot to follow up on this.
I made some changes, and I hope they will now pass the tests. If there are problems I would appreciate it if you can take over, since I don't have the time at the moment to locally install the project and its testing framework (I made the changes directly on my fork on github, given how simple the changes are).

**Comment by parano** [comment]
@omrihar thanks for updating the PR! it looks like the error message is a bit off in the test, just submitted a quick fix to that and everything is passing now!

**Comment by omrihar** [comment]
Great! Thanks for bringing this over the finish line ;)

**Pull request merged**
