### PR TITLE
ONNX-MLIR artifact 

### PR DESCRIPTION
**Pull request by andrewsi-z**
## Description
Creating a custom model artifact type for [ONNX-MLIR ](https://github.com/onnx/onnx-mlir) inference shared library object. 
ONNX-MLIR is an ONNX implementation that uses MLIR compiler infrastructure (a part of LLVM). 
It takes an ONNX model as input, and lowers it to varying IRs; this includes LLVM IR; ONNX-MLIR can compile and link the LLVM IR, creating a shared library object with a standard interface for inference.
For BentoML, we leverage the ONNX-MLIR PyRuntime interface documented here: http://onnx.ai/onnx-mlir//UsingPyRuntime.html
This requires a pybind binary that is built as part of ONNX-MLIR as a shared library under ONNX-MLIR. 

- Created a new artifact type in bentoml.frameworks.onnxmlir called OnnxMlirModelArtifact.
- Updated docs to include the new artifact type
- add example 
- add integration test script

## Motivation and Context
ONNX-MLIR is a relatively new project, and has some very attractive attributes that make it really interesting for use. 
- It generates a minimal viable program based on an ONNX model. This is a lightweight implementation.
- It can emit LLVM IR, which is highly portable (to any platform with an LLVM compiler). 
- The resulting program has little external dependencies. For platforms or architectures that do not have a deep ecosystem, this is a very elegant solution to deploy a model without having to worry about porting dependencies/requirements. 

see discussion here: https://github.com/bentoml/BentoML/discussions/905

## How Has This Been Tested?
A ResNet50 example can be found here: https://github.com/andrewsi-z/bento-onnxmlir-model-test
I will look to incorporate tests based on this into the project following discussion.

Environment Details:

    OS: macos big sur 11.2.1
    Python 3.8.5 
    
    ONNX-MLIR details:
    LLVM version 13.0.0git
    Optimized build with assertions.
    Default target: x86_64-apple-darwin20.3.0

    Also tested under ubuntu 20x
    

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [x] Test, CI, or build

## Component(s) if applicable
- [ ] BentoService (service definition, dependency management, API input/output adapters)
- [x] Model Artifact (model serialization, multi-framework support)
- [ ] Model Server (mico-batching, dockerisation, logging, OpenAPI, instruments)
- [ ] YataiService gRPC server (model registry, cloud deployment automation)
- [ ] YataiService web server (nodejs HTTP server and web UI)
- [ ] Internal (BentoML's own configuration, logging, utility, exception handling)
- [ ] BentoML CLI

## Checklist:

- [x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [x] My change reduces project test coverage and requires unit tests to be added
- [x] I have added unit tests covering my code change
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by andrewsi-z** [comment]
Keeping this in draft for discussion as there are a few things to resolve:
(For history, see discussion here: https://github.com/bentoml/BentoML/discussions/905)

I'm looking for guidance/opinion on:

1. How to Incorporate a test? 
ONNX-MLIR generates a shared library object (.so file). Building ONNX-MLIR requires LLVM and other dependencies.
( note pre-built containers are available). 
I need to think through a bit more how to incorporate ONNX-MLIR install (or pull a docker image) into the integration test process, and then handling the compile. Any thoughts would be appreciated.  

2. The build of ONNX-MLIR generates a required pybind library. This must be in the python path when the python interface (PyRuntime) is used. Is this something that should be packed or kept as a separate deployment requirement?

**Comment by andrewsi-z** [comment]
@yubozhao I believe this is nearing completion and almost ready to move out of draft.
I've been struggling with the container instance and a couple of pieces that I've been unlucky to find have changed underneath me.
The latest change should allow the model to compile, and on my local system I am able to validate the test case itself.
Unfortunately there is no great way to test locally the rest of the workflow as some of the actions are not supported by nektos act.

**Comment by andrewsi-z** [comment]
@parano @bojiang 
I'd like to move this forward; it appears since April 22nd all workflows for first time committers need approval (git hub wide).
Can you help me here? Would you like me to move this out of draft first?

**Comment by yubozhao** [comment]
@andrewsi-z just approved to run the CI.  I think we can also move it out of the draft.

**Comment by andrewsi-z** [comment]
Thanks @yubozhao  I've moved it out of draft

**Comment by yubozhao** [comment]
@andrewsi-z Can you fix the linter issue?

**Comment by andrewsi-z** [comment]
@yubozhao Yes, I will clean up now.

**Comment by yubozhao** [comment]
Seems like we are still failing with have `PyRuntime` missing from these stderr:
```
2021-05-07 21:01:15.414387: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /__t/Python/3.7.10/x64/lib
187
2021-05-07 21:01:15.414429: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
188
2021-05-07 21:01:15.414457: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (2cfe5f67895b): /proc/driver/nvidia/version does not exist
189
2021-05-07 21:01:15.414728: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
190
2021-05-07 21:01:15.421762: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2294685000 Hz
191
2021-05-07 21:01:15.422398: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f3634000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
192
2021-05-07 21:01:15.422442: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
```

You can find the log in the CI at https://github.com/bentoml/BentoML/pull/1545/checks?check_run_id=2531000293

**Comment by andrewsi-z** [comment]
Hi @yubozhao , thanks! 
I am working through that, I have the tests running in my fork now. If it's causing any issues with BentoML proper, I can just let you know when I have that resolved so the checks can be tried then here.
(For some reason, this is working locally but not here)

**Comment by andrewsi-z** [comment]
ok, I need to install curl during setup - let me handle that and make sure it works

**Comment by andrewsi-z** [comment]
@yubozhao No problem!
I think I have everything passing here. I see the project level code coverage, but I'm not sure I impacted that negatively (?)... As far as I can tell anyway.

**Comment by yubozhao** [comment]
Thank for you helping to make sure the test works!  I am going to merge it now @andrewsi-z

**Pull request merged**
