### PR TITLE
Enable PyLint on tests/integration

### LINKED ISSUE #1700: Enable PyLint on tests/integration
**Is your feature request related to a problem? Please describe.**

Currently the `make lint` task does not run `pylint` on the `tests/integration` folder. This is configured here in the `pylintrc` file: https://github.com/bentoml/BentoML/blob/master/pylintrc#L10

We would like to enable Pylint on this directory, remove it from the `ignore` list in the `pylintrc` file, and fix all the pylint errors found under that directory.

Note: some of the lint errors might be best to ignore inline with inline comment like this: `# pylint: disable=some-message,another-one`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes #1700

Hey @parano! How does this look?
I think this still needs some work, but if you have any review please use this space! thank you

### CODE REVIEW

**Comment by parano** [comment]
Hi @rbrishabh - thanks for getting started with this issue! looks like a good start!

You can now run `make lint` in the root directory and see all the lint errors from the `tests/integration/` directory, there are still quite a few of them remaining. You can also see the test results from the github CI links below, see details in the `BentoML-CI / lint_and_format` task.

**Comment by rbrishabh** [comment]
Thanks for the review @parano! Going to continue to work on this over the weekend :)

**Comment by bojiang** [comment]
For `E0401: Unable to import XXX`
We have three options.
1. install stubs
2. ignore E0401 for `tests/integration/*`
3. install all dependencies(h2o, tf, pytorch, etc)

@rbrishabh any idea about this?

**Comment by rbrishabh** [comment]
hi! I have a busy schedule and cant keep up with this now! Please feel free to continue it from here. I can close it for now

**Comment by aarnphm** [comment]
We will cover this in the next release

**Pull request closed without merging**
