### PR TITLE
fix(framework): add args and kwargs to sklearn and xgboost methods

### PR DESCRIPTION
**Pull request by jianshen92**
## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Review by aarnphm — APPROVED** [review]

**Comment by aarnphm** [comment]
one thing to note is that we might want to add partial kwargs to this as well

**Comment by jianshen92** [comment]
> one thing to note is that we might want to add partial kwargs to this as well

What kind of scenario does it solve?

**Comment by aarnphm** [comment]
If some kwargs that you want to set by default then using partial kwargs is useful.

**Comment by sauyon** [comment]
I'm not sure what you mean; surely the user just passes the non-optional kwargs?

**Pull request merged**
