### PR TITLE
Add Integration tests for Offline Batch Serving

### LINKED ISSUE #1379: Integration Tests for Offline Batch Serving
**Is your feature request related to a problem? Please describe.**

Right now, there are no integration tests for `bentoml run <bento> predict` for various adapters. I'd like to be able to ensure that there is no functionality regressions in being able to start inference jobs from the CLI while developing.

**Describe the solution you'd like**

Add integration tests for each adapter, targeting the `from_cli` function. Example in the base adapter: https://github.com/bentoml/BentoML/blob/fcecd97adb96ad30942150510ce335b086fed032/bentoml/adapters/base_input.py#L78

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jackyzha0**
## Description
Added pytorch image classification class to `tests/bento_service_examples`

## Motivation and Context
closes #1379

## How Has This Been Tested?
with written integration tests

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [x] Test, CI, or build

## Component(s) if applicable
- [ ] BentoService (service definition, dependency management, API input/output adapters)
- [ ] Model Artifact (model serialization, multi-framework support)
- [ ] Model Server (mico-batching, dockerisation, logging, OpenAPI, instruments)
- [ ] YataiService gRPC server (model registry, cloud deployment automation)
- [ ] YataiService web server (nodejs HTTP server and web UI)
- [ ] Internal (BentoML's own configuration, logging, utility, exception handling)
- [ ] BentoML CLI

## Checklist:

- [x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by yubozhao** [comment]
Looks good, make sure fix the linter issues.

**Comment by jackyzha0** [comment]
should be fixed, rerunning flaky tests

**Comment by yubozhao** [comment]
@jackyzha0 Do you know why the unit tests fail on ubuntu but not on Mac and windows?

**Comment by jackyzha0** [comment]
> @jackyzha0 Do you know why the unit tests fail on ubuntu but not on Mac and windows?

hmm not sure, it looks like its just timing out (these new integration tests take ~1min on my local machine), can we bump the timeout somehow?

**Comment by jackyzha0** [comment]
I've been poking around in CI logs for a few hours but still no clue why the unit tests could be timing out, maybe we could talk about this during our next sync

**Comment by yubozhao** [comment]
@jackyzha0 I rerun the tests and it went through.  Merged it.

**Pull request merged**
