### PR TITLE
chore(deps): `cattrs>=22.1.0` in setup.cfg

### LINKED ISSUE #2757: bug: Fix dependency version
### Describe the bug

The dependency `cattrs` has a version of `21.1.0`. But there is no such version (`21.1.0`) available on PyPI. Please update the version to the next existing version: `22.1.0`.

https://github.com/bentoml/BentoML/blob/64b296cdb8c327c3a53efa8ee95cf4b5e37502aa/setup.cfg#L41

source: https://pypi.org/project/cattrs/#history

image

### To reproduce

NA

### Expected behavior

The dependency-spec in `setup.cfg` should be: 

`cattrs >=22.1.0`

### Environment

bentoml: `v1.0.0`

### PR DESCRIPTION
**Pull request by sugatoray**
## What does this PR address?

Fixes #2757 

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request. :orange_circle: `TODO`
- [ ] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))? `NA`
- [x] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
  those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation). `NA`
- [ ] Did you write tests to cover your changes? `NA`

## Who can help review?

Feel free to tag members/contributors who can help review your PR.

### CODE REVIEW

**Comment by sugatoray** [comment]
cc: @parano @aarnphm

**Review by aarnphm — COMMENTED** [review]
We want to maintain the lowest version for compatibility, hence this change is rejected.

**Comment by sugatoray** [comment]
@aarnphm There is no such version `21.1.0` for `cattrs`. What you have in `setup.cfg` is a typo. Please see the associated issue #2757 .

**Comment by aarnphm** [comment]
see https://github.com/python-attrs/cattrs/tree/v22.1.0

**Comment by aarnphm** [comment]
Oh i see.

**Review by aarnphm — APPROVED** [review]

**Comment by parano** [comment]
Thanks for fixing this @sugatoray ! I think I ran into a warning about this at some point too. Does it fail installation for you completely? Did you figure how to reproduce the error?

**Comment by aarnphm** [comment]
> Thanks for fixing this @sugatoray ! I think I ran into a warning about this at some point too. Does it fail installation for you completely? Did you figure how to reproduce the error?

It fails on conda i believe

**Comment by sugatoray** [comment]
I was working on updating the conda-forge recipe. That's where I spotted this. I have not tried installing bentoml with cattrs `v22.1.0`. So, don't know if it will throw an error or not. But my guess is since `>=21.1.0` also includes `22.1.0` this will not show up with an obvious installation error.

**Pull request merged**
