### PR TITLE
[CI] Perform linting test during build

### PR DESCRIPTION
**Pull request by kautukkundan**
## Description

Modified linting script such that Travis builds will fail on linting errors

## Motivation and Context

To enforce no future linting errors arise

solves issue #711 

## How Has This Been Tested?

I created a Travis build environment for my forked repo and tested on that by deliberately adding linting errors

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation
- [x] Test, CI, or build
- [ ] None

## Components (if applicable)
- [ ] BentoService (model packaging, dependency management, handler definition)
- [ ] Model Artifact (model serialization, multi-framework support)
- [ ] Model Server (mico-batching, logging, metrics, tracing, benchmark, OpenAPI)
- [ ] YataiService (model management, deployment automation)
- [ ] Documentation

## Checklist:

- [x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] My change requires a change in [bentoml/gallery](https://github.com/bentoml/gallery) example notebooks
- [ ] I have sent a pull request to [bentoml/gallery](https://github.com/bentoml/gallery) to make that change

### CODE REVIEW

**Comment by kautukkundan** [comment]
@parano I wish to add that the windows build "occasionally" fails because it is unable to import "resource" module. I cannot find any solution for that. Please suggest what could be done?

**Comment by parano** [comment]
hi @kautukkundan, could you try add a separate job to run `lint.sh`? similar to how the `windows` job was setup. Here are related docs you may find helpful https://docs.travis-ci.com/user/build-matrix/   The linting script does not need to run in multiple OS or python versions, I think a separate task to run this script on Linux would be perfect

**Comment by kautukkundan** [comment]
@parano done.
Added a separate job which will only check for linting errors.

**Comment by parano** [comment]
This is super awesome! Thanks @kautukkundan!

**Comment by kautukkundan** [comment]
Thank you! It's fun working on the project 😄

**Pull request merged**
