### PR TITLE
fix: apply env map for distributed runner workers

### PR DESCRIPTION
**Pull request by bojiang**

### CODE REVIEW

**Comment by bojiang** [comment]
@sauyon  Here's a feature we will need to adopt to Rust in the future.

**Review by aarnphm — APPROVED** [review]

**Comment by sauyon** [comment]
Where is `scheduled_worker_env_map` set?

**Comment by aarnphm** [comment]
> Where is `scheduled_worker_env_map` set?

runners.py#L348

**Comment by sauyon** [comment]
Oh, it's from our scheduler. This seems like it should go away with our new architecture anyway, right? I feel like we should just remove all the resource stuff, anyway.

**Review by ssheng — APPROVED** [review]

**Pull request merged**
