### PR TITLE
feature(runner): add multiple output support

### PR DESCRIPTION
**Pull request by larme**
## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
  those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

## Who can help review?

Feel free to tag members/contributors who can help review your PR.

### CODE REVIEW

**Review by aarnphm — COMMENTED** [review]
is it possible to add a performance tests for this specific feature? I believe that having a regression test for this would be helpful so that we don't introduce features in the future that slow down the request?

**Comment by larme** [comment]
> is it possible to add a performance tests for this specific feature? I believe that having a regression test for this would be helpful so that we don't introduce features in the future that slow down the request?

just test this pr without noticeable performance difference. I'm making a script to manually launch a performance test but it needs some time to finish

**Comment by aarnphm** [comment]
> just test this pr without noticeable performance difference. I'm making a script to manually launch a performance test but it needs some time to finish

A think a script that run separately for this PR is good enough. I can follow up with a PR into a CI

**Review by aarnphm — APPROVED** [review]
Great work 😄

**Pull request merged**
