### PR TITLE
fix: typo in ALLOWED_CUDA_VERSION_ARGS

### PR DESCRIPTION
**Pull request by thomasjo**
## What does this PR address?

This PR fixes a typo in `ALLOWED_CUDA_VERSION_ARGS` that makes it impossible to set `cuda_version` in a bentofile.yaml file to to `'11.7'` or `'11.7.1'`.

It took me a while to track down the exact issue. At first I tried to simply specify my version as `'11.7.0'` to rely on that resolving to `'11.7.1'`. However, that doesn't work due to how the `cuda_version` attribute validation works: https://github.com/bentoml/BentoML/blob/7a83d993c57291a09c0c27a907d2815371bbf04f/src/bentoml/_internal/bento/build_config.py#L159-L165)

The bug was introduced in https://github.com/bentoml/BentoML/pull/4025. If the change was intended to act as a way to not introduce a breaking change and ensure that `'11.7.0'` maps to `'11.7.1'` instead, then it does not work as intended. For that to work the change in this PR needs to be added in addition to the original change introduced in #4025. I'm happy to make that change if wanted/needed.

As a side note, it seems like this functionality is not currently covered by any tests. I'd be happy to contribute to address that "blindspot" in a separate PR.

## Before submitting:

- [x] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [x] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [x] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by aarnphm** [comment]
Hey this is actually not a typo, rather there is no 11.7.0 tag on docker hub. https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.7.0

I will close this due to incorrect patch. Sorry

**Comment by sauyon** [comment]
Why do we have an 11.7.0 tag, then?

**Comment by aarnphm** [comment]
Oh my apology as I didn't read this clearly. I think what you need to add is a map to 11.7.1 to 11.7.1

**Review by sauyon — APPROVED** [review]

**Comment by thomasjo** [comment]
> Tests would be great if you're willing to contribute them!

@sauyon I'll try to find some time to implement some tests in the next few days.

**Pull request merged**
