### PR TITLE
fix: ignore user_defined_callback if it is a lambda function

### PR DESCRIPTION
**Pull request by aarnphm**
Signed-off-by: aarnphm-ec2-dev <29749331+aarnphm@users.noreply.github.com>

## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Review by sauyon — CHANGES_REQUESTED** [review]
Let's not make this change for a hack in our client. If we want to really support no func, let's support it with `None`, but I think we should just pass a real function to the client one.

**Comment by aarnphm** [comment]
@sauyon PTAL

**Review by sauyon — CHANGES_REQUESTED** [review]
You haven't addressed my comment.

**Comment by aarnphm** [comment]
Oh i realized I pushed the change to a different branch. let me open with the correct one.

**Pull request closed without merging**
