### PR TITLE
chore: add poetry metadata

### PR DESCRIPTION
**Pull request by sauyon**
We might want to do this eventually. There's versioneer-like functionality in a plugin but I haven't looked into it yet.

### CODE REVIEW

**Comment by sauyon** [comment]
Er @aarnphm did you intend to push that commit here?

**Comment by aarnphm** [comment]
> Er @aarnphm did you intend to push that commit here?

ye

**Comment by aarnphm** [comment]
> Er @aarnphm did you intend to push that commit here?

yep

**Comment by sauyon** [comment]
What's it have to do with this PR?

**Comment by aarnphm** [comment]
> What's it have to do with this PR?

oh I was thinking this is a chore pr, so just cleaning up unused files. I thought we already removed that files in previous PR but apparently not

**Comment by sauyon** [comment]
Should we just merge this? @parano

**Pull request merged**
