### PR TITLE
fix(model): lock attrs to >=21.1.0

### PR DESCRIPTION
**Pull request by bojiang**
## Description

fix: #2609 

## Checklist:

- [ ] My code follows the bentoml code style, both `make format` and
  `make lint` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by aarnphm** [comment]
We might need to check if this break cattrs.

**Comment by bojiang** [comment]
I didn't find the `cattrs` version compatibility in its docs. We can only try our best. I'd lock it to >= 1.9.0 because of python 3.10 support

**Comment by aarnphm** [comment]
If we locking attrs to 21.1.0, it might conflict with others library that is older attr.

**Comment by aarnphm** [comment]
> @aarnphm the current bentoml rc1 already requires `attrs>= 21.1.0` in fact. This PR doesn't change that. If users complained about that, we could open a larger PR to refactor to lower version APIs of attrs.

Our current API uses `attr` which is the underlying api, so compatibility issue on that front is not worrying. 

Seems that newer attrs version will have some features that are incompatible. @sauyon any inputs on this?

**Comment by sauyon** [comment]
It seems like `__attrs_init__` doesn't exist for older versions of attrs, this makes sense for me until somebody complains.

**Review by aarnphm — APPROVED** [review]

**Pull request merged**
