### PR TITLE
EasyOCR Artifact

### PR DESCRIPTION
**Pull request by gregd33**
## Description

Same code to use it would be:

```
@bentoml.artifacts([
    EasyOCRArtifact("chinese_small")
])
```
and 
```
service = EasyOCR()

lang_list = ['ch_sim', 'en']
recog_network = "zh_sim_g2"

model = easyocr.Reader(lang_list=lang_list, download_enabled=True, recog_network=recog_network )   
service.pack('chinese_small', model, lang_list=lang_list, recog_network= recog_network)

saved_path = service.save()

```

Artifact for [EasyOCR](https://github.com/JaidedAI/EasyOCR)

## Motivation and Context

See https://github.com/bentoml/BentoML/discussions/1538

## How Has This Been Tested?

In progress

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Component(s) if applicable
- [ ] BentoService (service definition, dependency management, API input/output adapters)
- [x] Model Artifact (model serialization, multi-framework support)
- [ ] Model Server (mico-batching, dockerisation, logging, OpenAPI, instruments)
- [ ] YataiService gRPC server (model registry, cloud deployment automation)
- [ ] YataiService web server (nodejs HTTP server and web UI)
- [ ] Internal (BentoML's own configuration, logging, utility, exception handling)
- [ ] BentoML CLI

## Checklist:

To do

- [x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [x] I have added unit tests covering my code change
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by yubozhao** [comment]
> One thing I'm uncertain about is if this is valid:
> 
> https://github.com/bentoml/BentoML/blob/9943276399583dc36ba79575f553e8f58554b4ff/bentoml/frameworks/easyocr.py#L53
> 
> Since the gpu will be determined on run time essentially (i.e. not when it is packed/saved) I thought it would make sense in `load` but am unsure how the user would use this arg.

Right now, it is difficult to modify the load behavior for model during loading BentoService.  The current practice for setting additional option is in `@artifacts` decorator when define bento service.  I think that's enough for most use-cases, where people would know ahead of using GPU or not in production.


> Another question: I'm writing some tests now and need an image to send. Where can I store this image to access it for the test?

You can store a small test image in the same directory as the test files

**Comment by gregd33** [comment]
Ready for review

**Comment by yubozhao** [comment]
@gregd33 It looks great

Thank you again for contributing to the community!

**Comment by gregd33** [comment]
Okay easyocr integration test now enabled and passing

**Comment by gregd33** [comment]
Realized that I omitted gpu completely instead of making it configurable at pack time. I've now fixed that.

**Comment by yubozhao** [comment]
> Realized that I omitted gpu completely instead of making it configurable at pack time. I've now fixed that.

Did you push that change? I can't seem to find it

**Comment by gregd33** [comment]
Thought I did but guess not. Pushed now

**Comment by yubozhao** [comment]
@gregd33 Merged Thank you for contributing!

**Pull request merged**
