### PR TITLE
docs: Add the yolo quickstart

### PR DESCRIPTION
**Pull request by Sherlock113**
## What does this PR address?

Add the Yolo quickstart.

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [x] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by aarnphm** [comment]
can you also run `pre-commit run --all-files` locally? ths. Otherwise LGTM

**Comment by Sherlock113** [comment]
@aarnphm Thanks. I ran it locally and it actually has too many errors😅, but the quickstart should be good as I did not find any error related to it.

image

**Comment by aarnphm** [comment]
Oh don't worry about the type issue. I think we just need to check if there is any whitespace issue.

**Review by aarnphm — APPROVED** [review]

**Comment by Sherlock113** [comment]
I see. It should be good now:
image

**Review by aarnphm — APPROVED** [review]

**Pull request merged**
