### PR TITLE
fix(build): make sure to install .tar.gz wheels

### PR DESCRIPTION
**Pull request by aarnphm**
this will fix installing bentoml dev wheels.

### CODE REVIEW

**Comment by frostming** [comment]
Why do we need to install tar.gz separately? the dev sdist will be added to the `requirements.txt`:

https://github.com/bentoml/BentoML/blob/a882bfbc25dd029d2a90bfbbf49b02200e773ca8/src/bentoml/_internal/bento/build_config.py#L591-L592

**Comment by aarnphm** [comment]
> Why do we need to install tar.gz separately? the dev sdist will be added to the `requirements.txt`:
> 
> https://github.com/bentoml/BentoML/blob/a882bfbc25dd029d2a90bfbbf49b02200e773ca8/src/bentoml/_internal/bento/build_config.py#L591-L592

currently we only check for ending with *.whl. this means .tar.gz won't be installed.

**Comment by frostming** [comment]
> currently we only check for ending with *.whl. this means .tar.gz won't be installed.

I mean we add them into the requirements.txt and it will be picked up by `pip install -r requirements.txt`

**Comment by aarnphm** [comment]
oh what happened to custom .tar.gz that can be installed with pip?

I guess I run into this issue with openllm, but then wrote a dockerfile template to install the custom .tar.gz separately.

edit: I think for this case users should write custom dockerfile template then, since installing arbitrary tar seems like a bad idea regardless.

**Comment by frostming** [comment]
> oh what happened to custom .tar.gz that can be installed with pip?

How to add these tarballs? we only support `python.wheels` in build config

**Comment by aarnphm** [comment]
hmm I guess `wheels=[wheel_fs.getsyspath(f"/{i.split('/')[-1]}") for i in built_wheels]`.

but probably out of scope. I don't think this is needed.

**Pull request closed without merging**
