### PR TITLE
fix(scheduling): expose Strategy class

### PR DESCRIPTION
**Pull request by bojiang**

### CODE REVIEW

**Comment by aarnphm** [comment]
Hmm can you run `pre-commit run --all-files` again? I thought we set our import lines to be single lines 🤔

**Comment by bojiang** [comment]
@aarnphm Tried. Nothing changed. It doesn't work.
I've upgraded black to the newest version.

**Comment by aarnphm** [comment]
hmm this is weird

**Comment by aarnphm** [comment]
cc @bojiang please update this with the merge conflict.

**Comment by aarnphm** [comment]
In light of #4068

**Pull request closed without merging**
