### PR TITLE
fix(deployment-client): add build process and extend url

### PR DESCRIPTION
**Pull request by Haivilo**
## What does this PR address?
1. Long url can be shown:
Screenshot 2024-06-11 at 2 30 13 AM

2. bento build progress is added:
Screenshot 2024-06-11 at 2 29 57 AM

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by frostming** [comment]
IMO the `Spinner` class is too complicated for such job, do you mind I propose something simpler?

**Comment by frostming** [comment]
Since #4796 is also ongoing let's keep the current implementation to avoid more conflicts.

We can refactor it after both are merged.

**Review by frostming — APPROVED** [review]

**Comment by frostming** [comment]
Hi, @Haivilo I've done some refactor around the Spinner class, you may need to update your PR. Thanks!

**Comment by Haivilo** [comment]
Thanks @frostming! I think the only change needed here now is to distinguish between using SDK or CLI. I have updated the PR; could you please take another look?

**Review by frostming — APPROVED** [review]

**Pull request merged**
