### PR TITLE
fix(type): `bentoml.container.build` should accept multiple `image_tag`

### PR DESCRIPTION
**Pull request by pmayd**
Correct type hint for `image_tag` so that the tuple can contain more than a single str element.

Currently, IDE (and mypy) is not accepting code like this:

```python
bentoml.container.build(
        bento_tag=model_bento.tag,
        image_tag=(
            "job-sectioning-model-opt:latest",
            f"job-sectioning-model-opt:{sys.argv[1]}"
        ),
        platform="linux/amd64"
    )
```

This is due to the fact that the type hint for `image_tag` is `tuple[str]` and not `tuple[str, ...]` for a tuple with an arbitrary length.

## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by sauyon** [comment]
This looks fine to me, was there a particular reason you closed this?

**Comment by pmayd** [comment]
I was not sure that I understood the code correctly, my change assumed that image_tag can indeed multiple tags but I guess it is indeed only meant to be a single value, that's why I closed it?

**Comment by aarnphm** [comment]
I think image_tag can accept multiple value, so your change is correct. We probably need a test for this as well.

**Review by aarnphm — APPROVED** [review]
I test this locally. Thanks for the fix

**Comment by sauyon** [comment]
Thanks for this!

**Pull request merged**
