### PR TITLE
Add default GPU docker base images

### PR DESCRIPTION
**Pull request by Sharathmk99**
## Description

#886 

## Motivation and Context

#886 

## How Has This Been Tested?

```
python ./guides/quick-start/main.py
cd $(bentoml get IrisClassifier:latest -q | jq -r ".uri.uri")
docker build -t bentoml-test .
docker run -p 5000:5000 bentoml-test:latest --enable-microbatch -w 2
```

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Component(s) if applicable
- [ ] BentoService (service definition, dependency management, API input/output adapters)
- [ ] Model Artifact (model serialization, multi-framework support)
- [ x] Model Server (mico-batching, dockerisation, logging, OpenAPI, instruments)
- [ ] YataiService gRPC server (model registry, cloud deployment automation)
- [ ] YataiService web server (nodejs HTTP server and web UI)
- [ ] Internal (BentoML's own configuration, logging, utility, exception handling)
- [ ] BentoML CLI

## Checklist:

- [ x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [x ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by parano** [comment]
Thanks for the PR @Sharathmk99 - you might need to merge with master branch in order to get the integration tests to pass on Travis.  There are also some code formatting error cause the build to fail, you can run `make format` on your local branch to fix the formatting issue.

**Comment by jackyzha0** [comment]
Is there a reason you chose to create a `Dockerfile-gpu` file rather than just providing a custom base image?

**Comment by gregd33** [comment]
Hi, this would be a useful feature to have. I looked at your commits to get it working for me temporarily (i.e. create a custom base image) and am confused by your Dockerfile. 

It uses  `nvidia/cuda:${CUDA_VERSION}-base` but this image doesn't seem to have python installed in it (at least for CUDA 11.0). The Dockerfile you provide fails to build at the pip install command.

On that note, your testing that you mention doesn't seem to test these changes and just builds the default IrisClassifier.

I might be missing something simple though, so apologies if so

**Comment by gregd33** [comment]
I've been looking at this a bit and came up with this as a Dockerfile which might be helpful. The parameterization needs some work and I have some extra installs, but the key idea of using the two base images seems to work. With this I was able to run a container with gpus.

```
ARG BENTO_VERSION="0.8.3"
ARG PYTHON_VERSION="37"
ARG CUDA_VERSION="11.0"

FROM bentoml/model-server:$BENTO_VERSION

FROM nvidia/cuda:${CUDA_VERSION}-cudnn8-runtime-ubuntu16.04

COPY --from=0 /opt/conda /opt/conda
ENV PATH /opt/conda/bin:$PATH

RUN python -m pip install --upgrade pip

RUN apt-get update --fix-missing && \
    apt-get install -y build-essential && \
    apt-get clean

WORKDIR /
```

**Pull request closed without merging**
