### PR TITLE
chore: bumping otlp deps to 1.15

### PR DESCRIPTION
**Pull request by aarnphm**
Courtesy of dependabot.

Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

### CODE REVIEW

**Comment by bojiang** [comment]
@aarnphm We don't have e2e tests for opentelemetry stuff now. Did you test them manually?

**Review by sauyon — DISMISSED** [review]

**Comment by sauyon** [comment]
You did test this right?

**Comment by aarnphm** [comment]
yep

**Review by sauyon — APPROVED** [review]

**Review by sauyon — APPROVED** [review]

**Comment by bojiang** [comment]
This change breaks monitoring feature.

**Pull request merged**
