### PR TITLE
fix(conda): python installation order

### PR DESCRIPTION
**Pull request by aarnphm**
it should install python first when using conda

### CODE REVIEW

**Comment by sauyon** [comment]
Can we add a quick test for this?

**Comment by sauyon** [comment]
Or would that be complex?

**Comment by aarnphm** [comment]
we need to set up e2e and smoke tests for this.

**Review by sauyon — APPROVED** [review]
Ok, if it'd take a while to do that let's just get this in; I assume you've tested a conda build?

**Pull request merged**
