### PR TITLE
chore(stubs): minify and remove unused

### PR DESCRIPTION
**Pull request by aarnphm**
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

### CODE REVIEW

**Comment by bojiang** [comment]
@aarnphm Is it possible to configure the black to keep the previous behavior about blank lines?

**Comment by bojiang** [comment]
It may cause tons of conflicts with current PRs

**Comment by bojiang** [comment]
Or can we configure or CI to only check the changed files? So the format style can be gradually changed.

**Comment by aarnphm** [comment]
> Or can we configure or CI to only check the changed files? So the format style can be gradually changed.

I don't know about this option because the blank lines is included in the stable release for 23.

We can also just merge all running PR in first to avoid this issue.

**Pull request closed without merging**
