### PR TITLE
Refactor multiprocessing set_start_method('fork') to initialization

### PR DESCRIPTION
**Pull request by ssheng**
## Description

Refactor multiprocessing set_start_method('fork') to the very beginning, before forking or spawning any process. The logic was added in response to the default start method change in multiprocess for MacOS. Ideally, the start method should be set before forking or spawning any processes. The original location in `bentoml/server/marshal_server.py` was not ideal because we have logic starting a new process before reaching that point in `bentoml/server/__init__.py`.

Thanks for the troubleshooting help from @yubozhao.

## Motivation and Context

Similar to gunicorn, dependency-injector requires the start method of new processes to be forking, to carry forward the containers and providers. Therefore, we should ensure start method is "fork" before starting any new processes.

## How Has This Been Tested?

./dev/format.sh
./dev/lint.sh
./ci/unit_test.sh

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature and improvements (non-breaking change which adds/improves functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Component(s) if applicable
- [ ] BentoService (service definition, dependency management, API input/output adapters)
- [ ] Model Artifact (model serialization, multi-framework support)
- [ ] Model Server (mico-batching, dockerisation, logging, OpenAPI, instruments)
- [ ] YataiService gRPC server (model registry, cloud deployment automation)
- [ ] YataiService web server (nodejs HTTP server and web UI)
- [ ] Internal (BentoML's own configuration, logging, utility, exception handling)
- [ ] BentoML CLI

## Checklist:

- [x] My code follows the bentoml code style, both `./dev/format.sh` and
  `./dev/lint.sh` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by bojiang — APPROVED** [review]

**Comment by bojiang** [comment]
I just enabled integration tests on MacOS. #1442

**Comment by bojiang** [comment]
@ssheng 
> Similar to gunicorn, dependency-injector requires the start method of new processes to be forking, to carry forward the containers and providers.

Hi ssheng, would you like to tell me the details of this?

I realized that it is not a good practice to set up the start method on importing bentoml, since some frameworks also requires a specific start method. Also, "fork" is not the recommended method today.

**Comment by ssheng** [comment]
Hi @bojiang, are you suggesting moving this to a later stage? The default multiprocess behavior is "fork" today except for Python 3.8 on Mac. Currently, Gunicorn requires the "fork" behavior.

**Comment by ssheng** [comment]
It seems like `set_start_method()` cannot be invoke more than once. We need the "fork" multiprocess behavior in Gunicorn and Dependency Injection. Do you think CLI package is a good place for setting this so it doesn't conflict with user code?

**Comment by parano** [comment]
@ssheng would this suggestion here: https://github.com/bentoml/BentoML/pull/1466#discussion_r581373525 help with the issue? I think, for now, the right place for `set_start_method` is where it was originally, in the Gunicorn related module, right before the fork.

There are quite a few other issues related to Gunicorn's fork behavior when it comes to serving on GPU instance, I think in the long run, we want to get rid of Gunicorn and manage multiple worker processes ourselves.

**Comment by ssheng** [comment]
Responded to https://github.com/bentoml/BentoML/pull/1466#discussion_r581373525. The short answer is that it wouldn't work unfortunately. We need "fork" behavior currently when we do multiprocesses involving mashal and gunicorn. A better place I can think of to `set_start_method()` is in `server/__init__.py`. Limit it to just the server package hopefully won't impact user model training and packing code.

**Pull request merged**
