### PR TITLE
chore: instsall git

### PR DESCRIPTION
**Pull request by xianml**
## What does this PR address?

Install git for 1.2  test
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! will remove this after we release 1.2

## Before submitting:

- [x] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by bojiang** [comment]
Why do we need git?

**Comment by xianml** [comment]
> Why do we need git?

for install bentoml from git source
only for bentocloud && bentoml test
image

**Comment by frostming** [comment]
we are planning to release alpha this week, then we can install with `BENTOML_VERSION=1.2.0a0`, for example.

**Comment by xianml** [comment]
> BENTOML_VERSION



> we are planning to release alpha this week, then we can install with `BENTOML_VERSION=1.2.0a0`, for example.

Okie then. will deprecate this PR

**Comment by aarnphm** [comment]
> > Why do we need git?
> 
> for install bentoml from git source only for bentocloud && bentoml test image

You can just include git into system_packages. It should be handled before the python.packages for now.

**Comment by xianml** [comment]
> > > Why do we need git?
> > 
> > 
> > for install bentoml from git source only for bentocloud && bentoml test image
> 
> You can just include git into system_packages. It should be handled before the python.packages for now.

Ohh. Great.

**Pull request closed without merging**
