### PR TITLE
fix(pandas): use correct mime type for Parquet

### PR DESCRIPTION
**Pull request by judahrand**
## What does this PR address?

It is a shame that BentoML doesn't use the correct mime type for Parquet:
https://www.iana.org/assignments/media-types/application/vnd.apache.parquet

Here we move to using the correct mime type going forwards but accept the old mime type too.

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

### CODE REVIEW

**Comment by judahrand** [comment]
@xianml I don't think these test failures are related to my changes

**Review by frostming — APPROVED** [review]

**Comment by frostming** [comment]
> @xianml I don't think these test failures are related to my changes

They are: https://github.com/bentoml/BentoML/actions/runs/9458228250/job/26053392444?pr=4780

**Comment by judahrand** [comment]
> > @xianml I don't think these test failures are related to my changes
> 
> They are: https://github.com/bentoml/BentoML/actions/runs/9458228250/job/26053392444?pr=4780

These failures aren't the ones I'd seen before - I'll look into them!

**Comment by judahrand** [comment]
> > @xianml I don't think these test failures are related to my changes
> 
> They are: https://github.com/bentoml/BentoML/actions/runs/9458228250/job/26053392444?pr=4780

I think I fixed the issue (it was a typo) but the tests seem to still be failing oddly. Passing on some platforms but failing on others which is strange given that my changes have absolutely nothing platform specific. Are these flakes that you're aware of?

**Comment by frostming** [comment]
🎉 Thanks

**Pull request merged**
